{{- if gt (.Values.deployment.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: tribeca-mapper-poddisruptionbudget
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      run: tribeca-mapper
  minAvailable: 1
{{- end }}
