name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    env:
      CI: true
      IMAGE_NAME: francescorivola/tribeca-mapper

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.4]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: superchargejs/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm run test-ci

    - name: Publish Code Coverage
      if: github.ref == 'refs/heads/master'
      uses: codecov/codecov-action@v1

    - name: Docker Build and Publish
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.IMAGE_NAME }}
        tag_with_ref: true
        tag_with_sha: true

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
